version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db
      - redis
    networks:
      - emotionbeats-network
    volumes:
      - ./coverage_reports:/app/coverage_reports
    command: sh -c "sleep 5 && python -m pytest -v tests/"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - SOCKETIO_REDIS_URL=redis://redis:6379/1
      - JWT_SECRET_KEY=testsecretkey
      - TESTING=True

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - emotionbeats-network

  redis:
    image: redis:7-alpine
    networks:
      - emotionbeats-network
    command: redis-server --appendonly no --maxmemory 128mb --maxmemory-policy allkeys-lru

networks:
  emotionbeats-network:
    driver: bridge