name: Backend CD

# This workflow is a placeholder for future deployment processes
# Uncomment and configure when deployment infrastructure is decided

on:
  workflow_dispatch:  # Manual trigger for now
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'backend/**'
  #   tags:
  #     - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Uncomment when ready to push to a registry
      # - name: Login to Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     # Configure for your chosen registry (Docker Hub, GHCR, ECR, etc.)
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: emotionbeats-backend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
      
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: false  # Change to true when ready to push
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Uncomment and configure when ready to deploy
  # deploy:
  #   name: Deploy Application
  #   runs-on: ubuntu-latest
  #   needs: build
  #   
  #   steps:
  #     - name: Deploy to Environment
  #       run: echo "Deployment step will be configured later"
